### ISSUE TITLE
Feature: Button to check MD5 and SHA1 sums, don't check automatically

### ISSUE THREAD

**Issue by akien-mga** [papoteur-mga/mageiaSync#1]
rsync + checking MD5 and SHA1 sums at the same time can be quite heavy on resources for the computer.

It would be nice if the checks were not done automatically, but if there was a button to start checking the ISOs (maybe between "Do sync" and "Stop"?), maybe with a parameter in the settings window to choose between MD5, SHA1 or both.

**Comment by akien-mga** [comment]
Another advantage would be that one would not have to rsync everything anew to get the ISOs tested. Since the current status of the ISOs is not saved (yet), it can be useful to perform e.g. MD5 sum checks to be sure that one's ISOs good.

**Comment by papoteur-mga** [comment]
The feature is added.
In Menu ->Sync -> Check
Only the selected files are checked

**Comment by akien-mga** [comment]
Great, thanks :-)
